version: '3'

services:

  mip-port:
    image: registry:5000/mip-port
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: mip-port
    ports:
    - 8087:80
    restart: unless-stopped

  mip-cache:
    image: registry:5000/mip-cache
    build:
      context: .
      dockerfile: Dockerfile.cache
    container_name: mip-cache
    # ports:
    # - 8087:80
    volumes:
    - mip-port-cache:/opt/nginx/cache
    restart: unless-stopped

volumes:
  mip-port-cache:
