version: '3'

services:

  mip-port:
    image: registry:5000/mip-port
    build: .
    container_name: mip-port
    ports:
    - 8087:80
    volumes:
    - mip-port-cache:/opt/nginx/cache
    restart: unless-stopped


volumes:
  mip-port-cache:
